package org.subclass.processor;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * Utility for generating properly formatted Java source code.
 * Handles class/interface generation with proper Javadoc, imports, and formatting.
 */
public class CodeGenerator {

    private static final DateTimeFormatter TIMESTAMP = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss");

    private final String packageName;
    private final String className;
    private final String classType; // "class", "interface", "record", etc.
    private final Set<String> imports;
    private final List<String> classJavadoc;
    private final List<String> classAnnotations;
    private final StringBuilder body;
    private String extendsClause; // For interface extends

    public CodeGenerator(String packageName, String className, String classType) {
        this.packageName = packageName;
        this.className = className;
        this.classType = classType;
        this.imports = new TreeSet<>();
        this.classJavadoc = new ArrayList<>();
        this.classAnnotations = new ArrayList<>();
        this.body = new StringBuilder();
        this.extendsClause = null;
    }

    public CodeGenerator addImport(String importStatement) {
        imports.add(importStatement);
        return this;
    }

    public CodeGenerator addImports(String... importStatements) {
        for (String stmt : importStatements) {
            imports.add(stmt);
        }
        return this;
    }

    public CodeGenerator addJavadoc(String line) {
        classJavadoc.add(line);
        return this;
    }

    public CodeGenerator addJavadocLines(String... lines) {
        for (String line : lines) {
            classJavadoc.add(line);
        }
        return this;
    }

    public CodeGenerator addAnnotation(String annotation) {
        classAnnotations.add(annotation);
        return this;
    }

    public CodeGenerator extendsClass(String parentClass) {
        this.extendsClause = parentClass;
        return this;
    }

    public CodeGenerator addBody(String code) {
        body.append(code);
        return this;
    }

    public String generate() {
        StringBuilder sb = new StringBuilder();

        // Package declaration
        sb.append("package ").append(packageName).append(";\n\n");

        // Imports
        if (!imports.isEmpty()) {
            for (String imp : imports) {
                sb.append("import ").append(imp).append(";\n");
            }
            sb.append("\n");
        }

        // Javadoc
        if (!classJavadoc.isEmpty()) {
            sb.append("/**\n");
            for (String line : classJavadoc) {
                sb.append(" * ").append(line).append("\n");
            }
            sb.append(" *\n");
            sb.append(" * <p><i>Generated by LogicGraphProcessor at ")
              .append(TIMESTAMP.format(LocalDateTime.now()))
              .append("</i>\n");
            sb.append(" */\n");
        }

        // Annotations
        for (String ann : classAnnotations) {
            sb.append(ann).append("\n");
        }

        // Class declaration
        sb.append("public ").append(classType).append(" ").append(className);
        if (extendsClause != null) {
            sb.append(" extends ").append(extendsClause);
        }
        sb.append(" {\n\n");

        // Body
        sb.append(body);

        // Closing brace
        sb.append("\n}\n");

        return sb.toString();
    }

    /**
     * Helper to generate a method stub with proper indentation.
     */
    public static String methodStub(String visibility, String returnType, String methodName,
                                    String parameters, String javadocLine) {
        StringBuilder sb = new StringBuilder();
        if (javadocLine != null && !javadocLine.isEmpty()) {
            sb.append("    /**\n");
            sb.append("     * ").append(javadocLine).append("\n");
            sb.append("     */\n");
        }
        sb.append("    ").append(visibility).append(" ")
          .append(returnType).append(" ")
          .append(methodName).append("(").append(parameters).append(");\n");
        return sb.toString();
    }

    /**
     * Helper to generate sealed interface declaration.
     */
    public static String sealedInterface(String visibility, String interfaceName,
                                         String... permitTypes) {
        StringBuilder sb = new StringBuilder();
        sb.append(visibility).append(" sealed interface ").append(interfaceName);
        if (permitTypes.length > 0) {
            sb.append("\n    permits ");
            for (int i = 0; i < permitTypes.length; i++) {
                if (i > 0) sb.append(", ");
                sb.append(permitTypes[i]);
            }
        }
        sb.append(" {}\n");
        return sb.toString();
    }

    /**
     * Helper to indent code blocks.
     */
    public static String indent(String code, int spaces) {
        String indentation = " ".repeat(spaces);
        return indentation + code.replace("\n", "\n" + indentation);
    }
}
